# Generated by scripts/homebrew-formula.sh in SoheilSalmani/weft on every
# release; do not edit by hand.
class Weft < Formula
  desc "Record-based project scaffolding"
  homepage "https://github.com/SoheilSalmani/weft"
  license any_of: ["MIT", "Apache-2.0"]

  head do
    url "https://github.com/SoheilSalmani/weft.git", branch: "master"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/SoheilSalmani/weft/releases/download/v0.1.0/weft-aarch64-apple-darwin.tar.gz"
      sha256 "9904cbbd2d38e6b9815d4948a1429bf2c32f4fd77c5de3e14459caf879c542bf"
    end
    on_intel do
      url "https://github.com/SoheilSalmani/weft/releases/download/v0.1.0/weft-x86_64-apple-darwin.tar.gz"
      sha256 "22ae7dc919f396695a3ed684d8b3f49a2bd6514d6d57c0f1561fdd9f5fe37647"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SoheilSalmani/weft/releases/download/v0.1.0/weft-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0d4ede135ae91a5f9e3256ee6f81f4c9aa5cf9ffccbf9c694eb590018bbebb2c"
    end
    on_intel do
      url "https://github.com/SoheilSalmani/weft/releases/download/v0.1.0/weft-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "be6d9992b8cc7d7032f5bd8d9e810d67e4d7806551a1c2b084473acf4f611924"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: "crates/weft-cli")
    else
      bin.install "weft"
    end
  end

  test do
    output = shell_output("#{bin}/weft --version")
    assert_match "weft ", output
    assert_match version.to_s, output unless build.head?
  end
end
